// <auto-generated />
using System;
using CourierMax.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourierMax.Data.Migrations
{
    [DbContext(typeof(CourierMaxContext))]
    [Migration("20260622024846_QuitarCiudadesDeEnvio")]
    partial class QuitarCiudadesDeEnvio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourierMax.Data.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Ciudades", "gral");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdTipoIdentificacion");

                    b.ToTable("Clientes", "core");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("IdVehiculo")
                        .IsUnique();

                    b.ToTable("Conductores", "core");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.DistanciaTarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("DistanciaKm")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCiudadDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdCiudadOrigen")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<decimal>("TarifaDistancia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCiudadDestino");

                    b.HasIndex("IdCiudadOrigen", "IdCiudadDestino")
                        .IsUnique();

                    b.ToTable("DistanciasTarifas", "gral");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Alto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CodigoRastreo")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("DireccionRecogida")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdConductor")
                        .HasColumnType("int");

                    b.Property<int>("IdDestinatario")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdRemitente")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPaquete")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoServicio")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadPeso")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadVolumen")
                        .HasColumnType("int");

                    b.Property<decimal>("Largo")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRastreo")
                        .IsUnique();

                    b.HasIndex("IdConductor");

                    b.HasIndex("IdDestinatario");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdRemitente");

                    b.HasIndex("IdTipoPaquete");

                    b.HasIndex("IdTipoServicio");

                    b.HasIndex("IdUnidadPeso");

                    b.HasIndex("IdUnidadVolumen");

                    b.ToTable("Envios", "core");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nomenclatura")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Estados", "gral");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.HistorialEstado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEnvio")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdEstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoNuevo")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Motivo")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("UsuarioCambio")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("IdEnvio");

                    b.HasIndex("IdEstadoAnterior");

                    b.HasIndex("IdEstadoNuevo");

                    b.ToTable("HistorialEstados", "core");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.TipoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Nomenclatura")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("TipoDetalles", "gral");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnuladoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<decimal>("CapacidadPesoKg")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("CapacidadVolumenM3")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ObservacionEstado")
                        .HasColumnType("varchar(250)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos", "core");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Cliente", b =>
                {
                    b.HasOne("CourierMax.Data.Entities.Ciudad", "Ciudad")
                        .WithMany("Clientes")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.TipoDetalle", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Conductor", b =>
                {
                    b.HasOne("CourierMax.Data.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Conductores")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.DistanciaTarifa", b =>
                {
                    b.HasOne("CourierMax.Data.Entities.Ciudad", "CiudadDestino")
                        .WithMany()
                        .HasForeignKey("IdCiudadDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.Ciudad", "CiudadOrigen")
                        .WithMany()
                        .HasForeignKey("IdCiudadOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CiudadDestino");

                    b.Navigation("CiudadOrigen");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Envio", b =>
                {
                    b.HasOne("CourierMax.Data.Entities.Conductor", "Conductor")
                        .WithMany("Envios")
                        .HasForeignKey("IdConductor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CourierMax.Data.Entities.Cliente", "Destinatario")
                        .WithMany()
                        .HasForeignKey("IdDestinatario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.Estado", "Estado")
                        .WithMany("Envios")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.Cliente", "Remitente")
                        .WithMany()
                        .HasForeignKey("IdRemitente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.TipoDetalle", "TipoPaquete")
                        .WithMany()
                        .HasForeignKey("IdTipoPaquete")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.TipoDetalle", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("IdTipoServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.TipoDetalle", "UnidadPeso")
                        .WithMany()
                        .HasForeignKey("IdUnidadPeso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.TipoDetalle", "UnidadVolumen")
                        .WithMany()
                        .HasForeignKey("IdUnidadVolumen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Destinatario");

                    b.Navigation("Estado");

                    b.Navigation("Remitente");

                    b.Navigation("TipoPaquete");

                    b.Navigation("TipoServicio");

                    b.Navigation("UnidadPeso");

                    b.Navigation("UnidadVolumen");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.HistorialEstado", b =>
                {
                    b.HasOne("CourierMax.Data.Entities.Envio", "Envio")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("IdEnvio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourierMax.Data.Entities.Estado", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("IdEstadoAnterior")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CourierMax.Data.Entities.Estado", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("IdEstadoNuevo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Envio");

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Ciudad", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Conductor", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Envio", b =>
                {
                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Estado", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("CourierMax.Data.Entities.Vehiculo", b =>
                {
                    b.Navigation("Conductores");
                });
#pragma warning restore 612, 618
        }
    }
}
